# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgAbout.resize(498, 497)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/gabrielgsd.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        dlgAbout.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dlgAbout)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setMinimumSize(QtCore.QSize(221, 221))
        self.label_2.setMaximumSize(QtCore.QSize(221, 221))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\templates\\../img/gabrielgsd.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=dlgAbout)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_close_about = QtWidgets.QPushButton(parent=dlgAbout)
        self.btn_close_about.setObjectName("btn_close_about")
        self.verticalLayout.addWidget(self.btn_close_about, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "About"))
        self.label_4.setText(_translate("dlgAbout", "Versión 0.0.1"))
        self.label_3.setText(_translate("dlgAbout", "Administración de usuarios"))
        self.label.setText(_translate("dlgAbout", "Gabrielgsd ©"))
        self.btn_close_about.setText(_translate("dlgAbout", "Close"))
