# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgAbout.resize(500, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/gabrielgsd.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setModal(True)
        self.btn_close_about = QtWidgets.QPushButton(parent=dlgAbout)
        self.btn_close_about.setGeometry(QtCore.QRect(210, 360, 75, 23))
        self.btn_close_about.setObjectName("btn_close_about")
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(190, 310, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setGeometry(QtCore.QRect(140, 0, 221, 221))
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\templates\\../img/gabrielgsd.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_3.setGeometry(QtCore.QRect(180, 290, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_4.setGeometry(QtCore.QRect(190, 250, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "About"))
        self.btn_close_about.setText(_translate("dlgAbout", "Close"))
        self.label.setText(_translate("dlgAbout", "Gabrielgsd ©"))
        self.label_3.setText(_translate("dlgAbout", "Administración de usuarios"))
        self.label_4.setText(_translate("dlgAbout", "Versión 0.0.1"))
