# Form implementation generated from reading ui file '.\templates\dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(414, 309)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a24gabrielsd/Documents/GitHub/Clases/2fps/diseño interfaces/pycharm/proyectos/SuarezDominguez/img/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgCalendar.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(dlgCalendar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Calendar = QtWidgets.QCalendarWidget(parent=dlgCalendar)
        self.Calendar.setGridVisible(True)
        self.Calendar.setObjectName("Calendar")
        self.gridLayout_2.addWidget(self.Calendar, 0, 0, 1, 1)

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Calendar"))
