# Form implementation generated from reading ui file '.\templates\dlgSettings.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(274, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/gabrielgsd.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        settings.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(settings)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_themes = QtWidgets.QLabel(parent=settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_themes.setFont(font)
        self.lbl_themes.setObjectName("lbl_themes")
        self.horizontalLayout.addWidget(self.lbl_themes)
        self.cb_themes = QtWidgets.QComboBox(parent=settings)
        self.cb_themes.setMinimumSize(QtCore.QSize(0, 28))
        self.cb_themes.setObjectName("cb_themes")
        self.horizontalLayout.addWidget(self.cb_themes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_cancel_settings = QtWidgets.QPushButton(parent=settings)
        self.btn_cancel_settings.setObjectName("btn_cancel_settings")
        self.horizontalLayout_3.addWidget(self.btn_cancel_settings)
        self.btn_save_settings = QtWidgets.QPushButton(parent=settings)
        self.btn_save_settings.setObjectName("btn_save_settings")
        self.horizontalLayout_3.addWidget(self.btn_save_settings)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.lbl_themes.setText(_translate("settings", "Themes: "))
        self.btn_cancel_settings.setText(_translate("settings", "Cancel"))
        self.btn_save_settings.setText(_translate("settings", "Save"))
